# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024-2026 Metixel Photoframe Contributors
"""Data models for Metixel Photoframe."""

from __future__ import annotations

import enum
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any


class MediaType(enum.Enum):
    IMAGE = "image"
    VIDEO = "video"


class TranscodeStatus(enum.Enum):
    """Transcoding state for a video media item."""

    NOT_TRANSCODED = "not_transcoded"  # Original file, transcoding not attempted
    TRANSCODING = "transcoding"  # Transcode in progress
    TRANSCODED = "transcoded"  # Cached transcoded file ready
    FAILED = "failed"  # Transcode failed, use original


@dataclass
class MediaItem:
    """Represents a single media asset ready for display."""

    id: str  # SHA-256 hash of original file
    original_path: Path
    cached_path: Path  # Path to processed (resized/transcoded) file
    media_type: MediaType
    width: int = 0
    height: int = 0
    duration_seconds: float = 0.0  # For videos
    thumbnail_path: Path | None = None
    first_frame_path: Path | None = None  # First frame JPEG (for video preload)
    last_frame_path: Path | None = None  # Last frame JPEG (for video swap)
    exif_data: dict[str, Any] = field(default_factory=dict)
    source: str = "local"  # "local" or "immich"
    transcode_status: TranscodeStatus | None = None  # Only relevant for videos
    failure_reason: str | None = None  # Why a video failed to process/transcode

    @property
    def aspect_ratio(self) -> float:
        if self.height > 0:
            return self.width / self.height
        return 1.0

    @property
    def is_ready_to_play(self) -> bool:
        """Whether this item can be played in the slideshow.

        Images are always ready.  Videos are only ready if:
        - The backend has explicitly set a transcode status (went through
          the optimisation pipeline), AND
        - The status is a playable one — ``TRANSCODED`` (cached) or
          ``NOT_TRANSCODED`` (already optimal, or transcoding disabled).
          ``FAILED`` is deliberately NOT playable: a video whose transcode
          failed must never fall back to playing the original at native
          resolution.  The presentation engine enforces this too.
        - First and last frame caches exist (generated by the backend
          during Phase 2: OPTIMISE — the frontend does NOT extract frames).
        A ``None`` status (e.g. from a dev fallback folder scan) means
        the item has not been through the optimisation pipeline — do NOT
        play it.
        """
        if self.media_type == MediaType.IMAGE:
            return True
        # Video: only play if the backend has explicitly set a status
        if self.transcode_status is None:
            return False  # Unknown — hasn't been through the pipeline
        if self.transcode_status not in (
            TranscodeStatus.TRANSCODED,
            TranscodeStatus.NOT_TRANSCODED,
        ):
            return False
        # Video: require first + last frame caches (backend-generated).
        # The frontend loads these directly — it must never run ffmpeg.
        return not (self.first_frame_path is None or self.last_frame_path is None)


@dataclass
class Album:
    """A named collection of media items."""

    id: str
    name: str
    items: list[MediaItem] = field(default_factory=list)
    source: str = "local"  # "local" or "immich"
    last_synced: float = 0.0  # Unix timestamp
