Section "ServerFlags"
    Option "DontZap" "true"
    Option "DontVTSwitch" "true"
    Option "AutoAddGPU" "false"
EndSection

Section "Device"
    Identifier "Card1"
    Driver "modesetting"
    BusID "PCI:0:0:0"
    Option "kmsdev" "/dev/dri/card1"
EndSection

Section "Screen"
    Identifier "Screen0"
    Device "Card1"
EndSection