# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024-2026 Metixel Photoframe Contributors
"""Tests for the OTA update bootstrap + install script.

These guard against regressions where an OTA upgrade applies the new code but
fails to install/update its dependencies — e.g. the bug where ``pillow-heif``
(needed for HEIC/HEIF media) was never installed because the OTA pip step only
ran ``pip install -e .`` and never installed ``requirements-pip.txt``.

The OTA bootstrap is generated by the currently-RUNNING update_manager.py, so
its dependency-install steps are handed off to ``scripts/ota_install.sh`` in the
freshly checked-out repository. That way a device upgrading from an older
release runs the NEW version's install logic.
"""

from __future__ import annotations

from pathlib import Path

from metixel.backend.update_manager import UpdateManager

# tests/backend/ -> repo root
_REPO_ROOT = Path(__file__).resolve().parents[2]
_INSTALL_SCRIPT = _REPO_ROOT / "scripts" / "ota_install.sh"


class TestBuildUpdateScript:
    def test_bootstrap_hands_off_to_install_script(self) -> None:
        """The generated bootstrap must run scripts/ota_install.sh from the
        freshly checked-out repo so the NEW version's install steps apply."""
        script = UpdateManager._build_update_script("/opt/metixel", "v1.0.0", "stable")

        assert "scripts/ota_install.sh" in script
        assert 'bash "$REPO/scripts/ota_install.sh" "$REPO"' in script
        # Services are still restarted via the EXIT trap.
        assert "systemctl restart metixel-backend metixel-cage" in script

    def test_quotes_external_values(self) -> None:
        """Externally-influenced values (ref/channel) are shell-quoted so they
        can't break out of the embedded bash string literals."""
        script = UpdateManager._build_update_script("/opt/metixel", "ref-with'quotes", "stable")

        # shlex.quote() wraps the apostrophe in a quoted splice, so the raw
        # contiguous value must not appear in the script.
        assert "ref-with'quotes" not in script


class TestInstallScript:
    """The install script is the single source of truth for dependency steps."""

    def test_install_script_exists(self) -> None:
        assert _INSTALL_SCRIPT.is_file(), (
            "scripts/ota_install.sh missing — the OTA bootstrap hands off to it"
        )

    def test_installs_runtime_pip_dependencies(self) -> None:
        """The install script must install requirements-pip.txt so new/changed
        runtime deps (e.g. pillow-heif) are applied on upgrade."""
        content = _INSTALL_SCRIPT.read_text(encoding="utf-8")

        assert "requirements-pip.txt" in content
        assert '-r "$REPO/requirements-pip.txt"' in content
        # The package reinstall step is still present.
        assert 'pip install --break-system-packages -e "$REPO"' in content

    def test_installs_system_packages(self) -> None:
        """The install script must also handle requirements-system.txt so new
        system deps are applied on upgrade, consistent with pip deps."""
        content = _INSTALL_SCRIPT.read_text(encoding="utf-8")

        assert "requirements-system.txt" in content
        assert "apt-get install" in content
