# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024-2026 Metixel Photoframe Contributors
"""Tests for the OTA update bootstrap + install script.

These guard against regressions where an OTA upgrade applies the new code but
fails to install/update its dependencies — e.g. the bug where ``pillow-heif``
(needed for HEIC/HEIF media) was never installed because the OTA pip step only
ran ``pip install -e .`` and never installed ``requirements-pip.txt``.

The OTA bootstrap is generated by the currently-RUNNING update_manager.py, so
its dependency-install steps are handed off to ``scripts/ota_install.sh`` in the
freshly checked-out repository. That way a device upgrading from an older
release runs the NEW version's install logic.
"""

from __future__ import annotations

from pathlib import Path

from metixel.backend.update_manager import UpdateManager

# tests/backend/ -> repo root
_REPO_ROOT = Path(__file__).resolve().parents[2]
_INSTALL_SCRIPT = _REPO_ROOT / "scripts" / "ota_install.sh"
_UPDATE_SCRIPT = _REPO_ROOT / "scripts" / "update.sh"


class TestBuildUpdateScript:
    def test_bootstrap_hands_off_to_update_script(self) -> None:
        """The generated bootstrap must delegate to scripts/update.sh (the
        atomic Blue/Green updater) so the NEW version's install steps apply."""
        script = UpdateManager._build_update_script("v1.0.0", "stable")

        assert "scripts/update.sh" in script
        assert 'bash "$UPDATE_SH" "$REF"' in script
        # Services are still restarted via the EXIT trap (safety net).
        assert "systemctl restart metixel-backend metixel-cage" in script
        # The ref is passed through to update.sh for git clone --branch.
        assert "v1.0.0" in script

    def test_quotes_external_values(self) -> None:
        """Externally-influenced values (ref/channel) are shell-quoted so they
        can't break out of the embedded bash string literals."""
        script = UpdateManager._build_update_script("ref-with'quotes", "stable")

        # shlex.quote() wraps the apostrophe in a quoted splice, so the raw
        # contiguous value must not appear in the script.
        assert "ref-with'quotes" not in script


class TestInstallScript:
    """The install script is the single source of truth for dependency steps."""

    def test_install_script_exists(self) -> None:
        assert _INSTALL_SCRIPT.is_file(), (
            "scripts/ota_install.sh missing — the OTA bootstrap hands off to it"
        )

    def test_installs_runtime_pip_dependencies(self) -> None:
        """The install script must install requirements-pip.txt so new/changed
        runtime deps (e.g. pillow-heif) are applied on upgrade."""
        content = _INSTALL_SCRIPT.read_text(encoding="utf-8")

        assert "requirements-pip.txt" in content
        assert '-r "$REPO/requirements-pip.txt"' in content
        # The package reinstall step is still present.
        assert 'pip install --break-system-packages -e "$REPO"' in content

    def test_installs_system_packages(self) -> None:
        """The install script must also handle requirements-system.txt so new
        system deps are applied on upgrade, consistent with pip deps."""
        content = _INSTALL_SCRIPT.read_text(encoding="utf-8")

        assert "requirements-system.txt" in content
        assert "apt-get install" in content

    def test_install_script_strict_by_default(self) -> None:
        """The install script must FAIL (not warn-and-continue) by default so
        the Blue/Green swap never happens on an incomplete install (e.g. when
        packages are unavailable offline)."""
        content = _INSTALL_SCRIPT.read_text(encoding="utf-8")

        # Strict mode aborts on failure.
        assert "_fail() { echo \"  ERROR: $* — aborting install\" >&2; exit 1; }" in content
        assert "aborting" in content

    def test_install_script_supports_continue_on_error_flag(self) -> None:
        """The legacy tolerant mode is preserved behind --continue-on-error for
        non-OTA contexts (e.g. startup dependency self-heal)."""
        content = _INSTALL_SCRIPT.read_text(encoding="utf-8")

        assert "--continue-on-error" in content
        assert "WARNING" in content

    def test_install_script_self_migrates_old_layout(self) -> None:
        """The install script must detect the old monolithic layout (no /data,
        no /live) and self-migrate to Blue/Green before installing, so the
        first upgrade through the existing OTA flow bridges to the new layout."""
        content = _INSTALL_SCRIPT.read_text(encoding="utf-8")

        assert "migrate_to_atomic.sh" in content
        assert "Old monolithic layout detected" in content
        # Runs with --no-restart (the OTA bootstrap handles the restart) and
        # --no-backup (the checkout just reset to the new code).
        assert "--no-restart" in content
        assert "--no-backup" in content
        # Re-points the working repo at the migrated release.
        assert "MIGRATED_RELEASE_DIR" in content

    def test_migrate_script_moves_logging_conf_to_data_etc(self) -> None:
        """logging.conf must move into /data/etc (not stay at /opt/metixel/etc) —
        __main__.py resolves it as data_dir()/etc/logging.conf, so all persistent
        config lives under /data."""
        mig = Path(__file__).resolve().parents[2] / "scripts" / "migrate_to_atomic.sh"
        content = mig.read_text(encoding="utf-8")

        # Both config.json and logging.conf move into /data.
        assert "config.json" in content
        assert "logging.conf" in content
        assert 'mv "${INSTALL_ROOT}/etc/logging.conf" "${DATA_DIR}/etc/logging.conf"' in content
        # No live/etc symlink is created (logging.conf is under /data now).
        assert 'ln -sfn "${INSTALL_ROOT}/etc" "${LIVE_LINK}/etc"' not in content

    def test_migrate_script_threads_install_root_into_heredoc(self) -> None:
        """The installed_packages.json recorder must honour $INSTALL_ROOT rather
        than hardcoding /opt/metixel."""
        mig = Path(__file__).resolve().parents[2] / "scripts" / "migrate_to_atomic.sh"
        content = mig.read_text(encoding="utf-8")

        assert 'python3 - "${INSTALL_ROOT}"' in content
        assert 'root = sys.argv[1]' in content
        assert 'root = "/opt/metixel"' not in content


class TestFixups:
    """Versioned device-repair fixups run once per device during install."""

    def test_fixup_manifest_and_scripts_exist(self) -> None:
        repo = Path(__file__).resolve().parents[2]
        manifest = repo / "scripts" / "fixups" / "manifest.txt"
        assert manifest.is_file()
        for line in manifest.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            assert (repo / "scripts" / "fixups" / line).is_file(), (
                f"fixup {line} listed in manifest but missing"
            )

    def test_install_script_runs_fixups(self) -> None:
        content = _INSTALL_SCRIPT.read_text(encoding="utf-8")

        assert "fixups/manifest.txt" in content
        assert "installed_fixups.json" in content
        # Fixups are warn-and-continue (do not abort the update).
        assert "WARNING: fixup" in content


class TestUpdateScript:
    """The atomic updater drives install + swap + rollback via update.sh."""

    def test_update_script_exists(self) -> None:
        assert _UPDATE_SCRIPT.is_file(), (
            "scripts/update.sh missing — the OTA bootstrap hands off to it"
        )

    def test_update_script_stages_and_swaps(self) -> None:
        content = _UPDATE_SCRIPT.read_text(encoding="utf-8")

        # Stages via git clone into a temp dir, then renames into releases/.
        assert "git clone --branch" in content
        assert "releases" in content
        # Atomic swap via symlink flip.
        assert "ln -sfn" in content
        assert "live" in content

    def test_update_script_has_rollback(self) -> None:
        content = _UPDATE_SCRIPT.read_text(encoding="utf-8")

        # Health-check + rollback path exists.
        assert "health" in content
        assert "ROLLING BACK" in content
        # config is backed up before the swap for rollback safety.
        assert "backups" in content
